"""Constants and lookup tables for weather decoding."""

from .common import (
    CHANGE_INDICATORS,
    CLOUD_TYPE_CODES,
    CLOUD_TYPES,
    CODE_GLOSSARY,
    DIRECTION_ABBREV,
    LIGHTNING_FREQUENCY,
    LIGHTNING_TYPES,
    LOCATION_INDICATORS,
    MAINTENANCE_INDICATOR,
    MILITARY_COLOR_CODES,
    PRESSURE_TENDENCY_CHARACTERISTICS,
    REPORT_MODIFIERS,
    RUNWAY_BRAKING,
    RUNWAY_BRAKING_REMARKS,
    RUNWAY_DEPOSIT_TYPES,
    RUNWAY_DEPTH_SPECIAL,
    RUNWAY_EXTENT,
    RUNWAY_STATE_DEPOSIT_TYPES_REMARKS,
    RUNWAY_STATE_EXTENT_REMARKS,
    RVR_TRENDS,
    SENSOR_STATUS,
    SKY_CONDITIONS,
    SPECIAL_CONDITIONS,
    SPECIAL_VALUES,
    STATION_TYPES,
    TREND_TYPES,
    WEATHER_DESCRIPTORS,
    WEATHER_INTENSITY,
    WEATHER_PHENOMENA,
)

__all__ = [
    # Weather
    "WEATHER_DESCRIPTORS",
    "WEATHER_INTENSITY",
    "WEATHER_PHENOMENA",
    # Sky
    "CLOUD_TYPE_CODES",
    "CLOUD_TYPES",
    "SKY_CONDITIONS",
    # Runway
    "RUNWAY_BRAKING",
    "RUNWAY_BRAKING_REMARKS",
    "RUNWAY_DEPOSIT_TYPES",
    "RUNWAY_DEPTH_SPECIAL",
    "RUNWAY_EXTENT",
    "RUNWAY_STATE_DEPOSIT_TYPES_REMARKS",
    "RUNWAY_STATE_EXTENT_REMARKS",
    "RVR_TRENDS",
    # Pressure
    "PRESSURE_TENDENCY_CHARACTERISTICS",
    # Location
    "DIRECTION_ABBREV",
    "LIGHTNING_FREQUENCY",
    "LIGHTNING_TYPES",
    "LOCATION_INDICATORS",
    # Change codes
    "CHANGE_INDICATORS",
    "TREND_TYPES",
    # Military
    "MILITARY_COLOR_CODES",
    # Report / station
    "REPORT_MODIFIERS",
    "SPECIAL_CONDITIONS",
    "SPECIAL_VALUES",
    "STATION_TYPES",
    "SENSOR_STATUS",
    "MAINTENANCE_INDICATOR",
    "CODE_GLOSSARY",
]
