"""Master glossary of METAR/TAF-related abbreviations.

This is a human-facing reference table intended to answer: "What does this
token/code mean?" across METAR/TAF body groups and common remarks.

Parsing/validation code should usually rely on more specific tables (e.g.
`weather_codes.py`, `sky_codes.py`, `runway_codes.py`, etc.). This glossary is
deliberately broader and may include items that are not parsed as standalone
groups (e.g., unit abbreviations or contextual acronyms).
"""

# NOTE: Some keys contain spaces or slashes (e.g. "PK WND", "L / C / R") because
# they appear that way in common reference material.
CODE_GLOSSARY = {
    "+": "Heavy intensity / indicator that visual range data follows",
    "+FC": "Tornado or waterspout",
    "-": "Light intensity",
    "/": "Separator between temperature and dew point",
    "00000KT": "Calm",
    "A01": "Reported by automated observation equipment that CANNOT distinguish between rain and snow",
    "A02": "Reported by automated observation equipment that CAN distinguish between rain and snow",
    "A02A": "Automated, human-augmented",
    "ACC": "Altocumulus castellanus",
    "ACFT MSHP": "Aircraft mishap",
    "ACSL": "Altocumulus standing lenticular cloud",
    "ALP": "Airport location point",
    "AMD": "Amended",
    "AO1": "Automated station without precipitation discriminator",
    "AO2": "Automated station with precipitation discriminator",
    "APCH": "Approach",
    "APRNT": "Apparent",
    "APRX": "Approximately",
    "ATCT": "Airport traffic control tower",
    "AUTO": "Fully automated report (no human intervention)",
    "B": "Began",
    "BC": "Patches",
    "BECMG": "Gradual change",
    "BECMG DDHH/DDHH": "Becoming (gradual change)",
    "BKN": "Broken (5–7 oktas)",
    "BL": "Blowing",
    "BR": "Mist (≥ 5/8 SM)",
    "C": "Center (runway reference)",
    "CA": "Cloud–air lightning",
    "CAVOK": "Ceiling ≥5000 ft AND visibility ≥10 km AND no significant weather",
    "CB": "Cumulonimbus (METAR & TAF)",
    "CBMAM": "Cumulonimbus mammatus cloud",
    "CC": "Cloud–cloud lightning",
    "CCSL": "Cirrocumulus standing lenticular cloud",
    "CG": "Cloud–ground lightning",
    "CHI": "Cloud-height indicator",
    "CHINO": "Sky condition at secondary location not available",
    "CIG": "Ceiling",
    "CLR": "Clear",
    "CONS": "Continuous",
    "COR": "Correction to a previously disseminated observation",
    "DOC": "Department of Commerce",
    "DOD": "Department of Defense",
    "DOT": "Department of Transportation",
    "DR": "Low drifting",
    "DS": "Dust storm",
    "DSIPTG": "Dissipating",
    "DSNT": "Distant",
    "DU": "Widespread dust",
    "DVR": "Dispatch visual range",
    "DZ": "Drizzle",
    "E": "East / Ended / Estimated ceiling (SAO)",
    "FAA": "Federal Aviation Administration",
    "FC": "Funnel cloud",
    "FEW": "Few (1–2 oktas)",
    "FEW000 / SCT000 / BKN000": "Surface-based obscuration layer groups (not a ceiling)",
    "FG": "Fog (< 5/8 SM)",
    "FIBI": "Filed but impracticable to transmit",
    "FIRST": "First observation after a break in coverage",
    "FM": "Rapid change, replaces previous line",
    "FMDDHHMM": "From (rapid change, new line)",
    "FMH-1": "Federal Meteorological Handbook No. 1 (METAR)",
    "FMH-2": "Federal Meteorological Handbook No. 2",
    "FROPA": "Frontal passage",
    "FRQ": "Frequent",
    "FT": "Feet (U.S.)",
    "FU": "Smoke",
    "FZ": "Freezing",
    "FZRANO": "Freezing rain sensor not available",
    "G": "Gusts (e.g., G25)",
    "GR": "Hail",
    "GS": "Small hail and/or snow pellets",
    "HLSTO": "Hailstone",
    "HZ": "Haze",
    "IC": "Ice crystals / In-cloud lightning",
    "ICAO": "International Civil Aviation Organization",
    "INCRG": "Increasing",
    "INTMT": "Intermittent",
    "KT": "Knots",
    "L": "Left (runway reference)",
    "L / C / R": "Left / Center / Right runway",
    "LAST": "Last observation before a break",
    "LST": "Local Standard Time",
    "LTG": "Lightning",
    "LWR": "Lower",
    "M": "Minus (below 0 °C)",
    "M / P": "Less than / Greater than reportable value",
    "METAR": "Routine hourly observation (normally :50–:59)",
    "MI": "Shallow",
    "MOV": "Moved / Moving / Movement",
    "MT": "Mountains",
    "N": "North",
    "N/A": "Not applicable",
    "NCDC": "National Climatic Data Center",
    "NE": "Northeast",
    "NOS": "National Ocean Survey",
    "NOSPECI": "No SPECI reports taken",
    "NOTAM": "Notice to Airmen",
    "NSW": "No significant weather expected",
    "NW": "Northwest",
    "NWS": "National Weather Service",
    "OCNL": "Occasional",
    "OFCM": "Office of the Federal Coordinator for Meteorology",
    "OHD": "Overhead",
    "OVC": "Overcast (8 oktas)",
    "OVR": "Over",
    "P": "Greater than highest reportable value",
    "P6SM": "Visibility greater than 6 SM (TAF)",
    "PCPN": "Precipitation",
    "PK WND": "Peak wind",
    "PL": "Ice pellets",
    "PNO": "Precipitation amount not available",
    "PO": "Dust/sand whirls",
    "PR": "Partial",
    "PRES": "Pressure",
    "PRESFR": "Pressure falling rapidly",
    "PRESRR": "Pressure rising rapidly",
    "PRESRR / PRESFR": "Pressure rising rapidly / pressure falling rapidly",
    "PROB30 / PROB40": "Probability (civilian only)",
    "PWINO": "Precipitation identifier sensor not available",
    "PY": "Spray",
    "R": "Runway visual range",
    "RA": "Rain",
    "RMK": "Remarks indicator",
    "RTD": "Routine delayed observation",
    "RV": "Reportable value",
    "RVR": "Runway visual range",
    "RVRNO": "RVR system not available",
    "RY": "Runway",
    "S": "Snow / South",
    "SA": "Sand",
    "SCSL": "Stratocumulus standing lenticular cloud",
    "SCT": "Scattered (3–4 oktas)",
    "SE": "Southeast",
    "SFC": "Surface",
    "SG": "Snow grains",
    "SH": "Showers",
    "SKC": "Sky clear",
    "SKC / CLR": "Sky clear",
    "SLP": "Sea-level pressure",
    "SLPNO": "Sea-level pressure not available",
    "SM": "Statute miles (U.S.)",
    "SN": "Snow",
    "SNINCR": "Snow increasing rapidly",
    "SP": "Snow pellets",
    "SPECI": "Special unscheduled observation (significant changes)",
    "SQ": "Squalls",
    "SS": "Sandstorm",
    "STN": "Station",
    "SW": "Snow shower / Southwest",
    "TAF": "Terminal Aerodrome Forecast",
    "TAF AMD": "Amended TAF",
    "TCU": "Towering cumulus (METAR only)",
    "TEMPO": "Temporary (<1 hr at a time)",
    "TEMPO DDHH/DDHH": "Temporary fluctuations (<1 hr at a time)",
    "TESTM": "Non-commissioned ASOS report",
    "TS": "Thunderstorm",
    "TSNO": "Thunderstorm information not available",
    "TT/DD": "Degrees Celsius",
    "TWR": "Tower",
    "UNKN": "Unknown",
    "UP": "Unknown precipitation (automated)",
    "UTC": "Coordinated Universal Time",
    "V": "Variable",
    "VA": "Volcanic ash",
    "VC": "Vicinity (5–10 SM in U.S.)",
    "VIRGA": "Precipitation not reaching ground",
    "VIS": "Visibility",
    "VISNO": "Visibility at secondary location not available",
    "VR": "Visual range",
    "VRB": "Variable wind direction",
    "VV": "Vertical visibility",
    "W": "West",
    "WG/SO": "Working Group for Surface Observations",
    "WMO": "World Meteorological Organization",
    "WND": "Wind",
    "WSCONDS": "Possible shear, insufficient data (often beyond 6 hrs)",
    "WSHFT": "Wind shift",
    "Z": "Zulu time (UTC)",
}
